name: gaussian_splatting_reduced
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cuda-toolkit=12.3.2
  - plyfile
  - python=3.8
  - pip=22.3.1
  - pytorch=2.3.1
  - torchaudio
  - torchvision
  - tqdm
